name: Build Aseprite (Windows Manual)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare MSVC build environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja and CMake
        run: choco install ninja cmake -y

      - name: Download Skia
        shell: bash
        run: |
          skia_url=$(source laf/misc/skia-url.sh | xargs)
          skia_file=$(basename "$skia_url")
          echo "Downloading $skia_file..."
          curl -L -o "$skia_file" "$skia_url"
          unzip -q "$skia_file" -d skia

      - name: Configure build
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DLAF_BACKEND=skia \
            -DENABLE_SCRIPTING=ON \
            -DENABLE_UPDATER=OFF \
            -DENABLE_TELEMETRY=OFF \
            -DSKIA_DIR=$(realpath skia) \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)

      - name: Build Aseprite
        shell: bash
        run: |
          cd build
          ninja aseprite

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-windows
          path: build/bin/aseprite.exe
